error on line 186
```
>>> 3 ^ 2 = 3 x 3
  File "<stdin>", line 1
    3 ^ 2 = 3 x 3
    ^
SyntaxError: cannot assign to operator
>>> 3 ^ 2 = 3 x 3 = 9
  File "<stdin>", line 1
    3 ^ 2 = 3 x 3 = 9
    ^
SyntaxError: cannot assign to operator
```

changed to show square root calc properly and x was just shown above as not valid syntax earlier